### ISSUE TITLE
broken build due to character literals

### ISSUE THREAD

**Issue by sgajjar** [cmusphinx/sphinx4#43]
The simpletokenizer.java and USEnglishTokenizer.java are causing issue with character literals while building using gradle. Please help!

**Comment by nshmyrev** [comment]
What kind of issue exactly? Please provide more details

**Comment by sgajjar** [comment]
$ gradle jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:sphinx4-core:compileJavaC:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: unmappable character for encoding Cp1252
        text = text.replace('▒?', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:18: error: unclosed character literal
        text = text.replace('’', '\'');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:18: error: ';' expected
        text = text.replace('’', '\'');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:18: error: illegal character: '\u2122'
        text = text.replace('’', '\'');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:18: error: unclosed character literal
        text = text.replace('’', '\'');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:18: error: not a statement
        text = text.replace('’', '\'');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:18: error: ';' expected
        text = text.replace('’', '\'');
                                       ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:19: error: unclosed character literal
        text = text.replace('‘', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:19: error: ';' expected
        text = text.replace('‘', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:19: error: illegal character: '\u02dc'
        text = text.replace('‘', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:19: error: unclosed character literal
        text = text.replace('‘', ' ');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:19: error: not a statement
        text = text.replace('‘', ' ');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:19: error: ';' expected
        text = text.replace('‘', ' ');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: unclosed character literal
        text = text.replace('▒?', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: ';' expected
        text = text.replace('▒?', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: illegal character: '\ufffd'
        text = text.replace('▒?', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: unclosed character literal
        text = text.replace('▒?', ' ');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: not a statement
        text = text.replace('▒?', ' ');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:20: error: ';' expected
        text = text.replace('▒?', ' ');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:21: error: unclosed character literal
        text = text.replace('“', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:21: error: ';' expected
        text = text.replace('“', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:21: error: unclosed character literal
        text = text.replace('“', ' ');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:21: error: ';' expected
        text = text.replace('“', ' ');
                                  ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:21: error: illegal start of expression
        text = text.replace('“', ' ');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:23: error: unclosed character literal
        text = text.replace('»', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:23: error: illegal character: '\u00bb'
        text = text.replace('»', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:23: error: unclosed character literal
        text = text.replace('»', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:23: error: ';' expected
        text = text.replace('»', ' ');
                                 ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:23: error: illegal start of expression
        text = text.replace('»', ' ');
                                     ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:24: error: unclosed character literal
        text = text.replace('«', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:24: error: illegal character: '\u00ab'
        text = text.replace('«', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:24: error: unclosed character literal
        text = text.replace('«', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:24: error: ';' expected
        text = text.replace('«', ' ');
                                 ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:24: error: illegal start of expression
        text = text.replace('«', ' ');
                                     ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:25: error: unclosed character literal
        text = text.replace('–', '-');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:25: error: ';' expected
        text = text.replace('–', '-');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:25: error: illegal character: '\u201c'
        text = text.replace('–', '-');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:25: error: unclosed character literal
        text = text.replace('–', '-');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:25: error: not a statement
        text = text.replace('–', '-');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:25: error: ';' expected
        text = text.replace('–', '-');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:26: error: unclosed character literal
        text = text.replace('—', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:26: error: ';' expected
        text = text.replace('—', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:26: error: illegal character: '\u201d'
        text = text.replace('—', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:26: error: unclosed character literal
        text = text.replace('—', ' ');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:26: error: not a statement
        text = text.replace('—', ' ');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:26: error: ';' expected
        text = text.replace('—', ' ');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:27: error: unclosed character literal
        text = text.replace('…', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:27: error: ';' expected
        text = text.replace('…', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:27: error: illegal character: '\u00a6'
        text = text.replace('…', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:27: error: unclosed character literal
        text = text.replace('…', ' ');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:27: error: not a statement
        text = text.replace('…', ' ');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\SimpleTokenizer.java:27: error: ';' expected
        text = text.replace('…', ' ');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: unmappable character for encoding Cp1252
        text = text.replace('▒?', '"');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:425: error: unclosed character literal
        text = text.replace('’', '\'');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:425: error: ';' expected
        text = text.replace('’', '\'');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:425: error: illegal character: '\u2122'
        text = text.replace('’', '\'');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:425: error: unclosed character literal
        text = text.replace('’', '\'');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:425: error: not a statement
        text = text.replace('’', '\'');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:425: error: ';' expected
        text = text.replace('’', '\'');
                                       ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:426: error: unclosed character literal
        text = text.replace('‘', '\'');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:426: error: ';' expected
        text = text.replace('‘', '\'');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:426: error: illegal character: '\u02dc'
        text = text.replace('‘', '\'');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:426: error: unclosed character literal
        text = text.replace('‘', '\'');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:426: error: not a statement
        text = text.replace('‘', '\'');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:426: error: ';' expected
        text = text.replace('‘', '\'');
                                       ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: unclosed character literal
        text = text.replace('▒?', '"');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: ';' expected
        text = text.replace('▒?', '"');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: illegal character: '\ufffd'
        text = text.replace('▒?', '"');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: unclosed character literal
        text = text.replace('▒?', '"');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: not a statement
        text = text.replace('▒?', '"');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:427: error: ';' expected
        text = text.replace('▒?', '"');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:428: error: unclosed character literal
        text = text.replace('“', '"');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:428: error: ';' expected
        text = text.replace('“', '"');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:428: error: unclosed character literal
        text = text.replace('“', '"');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:428: error: ';' expected
        text = text.replace('“', '"');
                                  ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:428: error: illegal start of expression
        text = text.replace('“', '"');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:429: error: unclosed character literal
        text = text.replace('»', '"');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:429: error: illegal character: '\u00bb'
        text = text.replace('»', '"');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:429: error: unclosed character literal
        text = text.replace('»', '"');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:429: error: ';' expected
        text = text.replace('»', '"');
                                 ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:429: error: illegal start of expression
        text = text.replace('»', '"');
                                     ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:430: error: unclosed character literal
        text = text.replace('«', '"');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:430: error: illegal character: '\u00ab'
        text = text.replace('«', '"');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:430: error: unclosed character literal
        text = text.replace('«', '"');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:430: error: ';' expected
        text = text.replace('«', '"');
                                 ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:430: error: illegal start of expression
        text = text.replace('«', '"');
                                     ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:431: error: unclosed character literal
        text = text.replace('–', '-');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:431: error: ';' expected
        text = text.replace('–', '-');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:431: error: illegal character: '\u201c'
        text = text.replace('–', '-');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:431: error: unclosed character literal
        text = text.replace('–', '-');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:431: error: not a statement
        text = text.replace('–', '-');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:431: error: ';' expected
        text = text.replace('–', '-');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:432: error: unclosed character literal
        text = text.replace('—', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:432: error: ';' expected
        text = text.replace('—', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:432: error: illegal character: '\u201d'
        text = text.replace('—', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:432: error: unclosed character literal
        text = text.replace('—', ' ');
                                ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:432: error: not a statement
        text = text.replace('—', ' ');
                                   ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:432: error: ';' expected
        text = text.replace('—', ' ');
                                      ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:433: error: unclosed character literal
        text = text.replace('…', ' ');
                            ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:433: error: ';' expected
        text = text.replace('…', ' ');
                              ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:433: error: illegal character: '\u00a6'
        text = text.replace('…', ' ');
                               ^
C:\Users\sgajjar\Documents\IdeaProjects\sphinx4\sphinx4-core\src\main\java\edu\cmu\sphinx\alignment\USEnglishTokenizer.java:433: error: unclosed character literal
        text = text.replace('…', ' ');
                                ^
100 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sphinx4-core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.07 secs

**Comment by nshmyrev** [comment]
Should be fixed now, thank you for the report.

**Comment by cricket1** [comment]
I have the latest code (5aee3e042cef81fb5db3c1f887ed240dca7edd97)  .I still see the same issue

**Comment by amitsingh21** [comment]
i am also getting the same issue

**Comment by nshmyrev** [comment]
Ok, I have fixed the code again, now it should build. Please update and try again and let me know if it works. 

Thank you

**Comment by Delaley** [comment]
Sorry just grabbed this version am getting the same problem

**Comment by nshmyrev** [comment]
You need to provide more details

**Comment by SamWibatt** [comment]
This is happening to me now - it looks like the tokenizer is trying to de-Microsoft text, and ending up with lines like this, that I just copied out of USEnglishTokenizer.java:
text = text.replace('â€™', '\'');
i.e., text prepared in Microsoft tools with "smart quotes" and such and then copied/pasted into normal text files gets a bunch of garbage like that. Things like that have caused me no end of headaches in text processing, and I'm happy to see CMUSphinx takes steps to get rid of it.
However, the 'â€™' is identified as an illegal constant because, I guess, it's multiple characters within single quotes. It looks like it might be truly fixable by getting rid of â€ in all the Microsofty lines. That's what I'm going to do to fix it, and hope it works.
